### ISSUE TITLE
Soft lock when clicking the event queue button for CAs after the Black site cut scene

### ISSUE THREAD

**Issue by DerRoberto** [WOTCStrategyOverhaul/CovertInfiltration#109]
after the cut scene where the blacksite is revealed played clicking on the event queue button for the covert actions ![inked20190219144318_1_li](https://user-images.githubusercontent.com/47782227/53019395-ed05fa80-3454-11e9-93b9-972c97973fd9.jpg)
the CA screen opens, when closing the screen the camera will pan to the blacksite and you get soft locked. 
![20190219134329_1](https://user-images.githubusercontent.com/47782227/53019584-584fcc80-3455-11e9-9bff-2ec65d843b07.jpg)

**Comment by Xymanek** [comment]
So turns out fixing this issue is somewhat complicated. The reason being is that the "world clock" ticks (which is normally used for forcing the player into the screen) before the blacksite camera panning (and screen) happens.

It's possible to fix this issue but requires keeping quite a bit of state about where the player is in the avenger + reacting to multitude of UI and gamestate events
