### ISSUE TITLE
Bradford should not nag about having too many soldiers doing CAs

### ISSUE THREAD

**Issue by Samio321** [WOTCStrategyOverhaul/CovertInfiltration#194]
When the player has a large percentage of people involved in covert actions, he will nag the player saying that this is a bad thing, which may mislead players. This shouldn't happen.
Edit: Wanted to clarify that the message about over-involvement comes in during squad selection.

**Comment by Xymanek** [comment]
This is a warning by the game itself, although we kept it in to "hint" the player that they shouldn't send everybody out. Perhaps it needs a slight improvement

**Comment by Xymanek** [comment]
We should remove it from infil loadout, since it duplicates the vanilla "less than x soldiers" nag

**Comment by Xymanek** [comment]
So.... interesting enough I cannot find "vanilla nag" neither in code, neither in practice, so I have no clue what I was talking about back then

**Comment by Xymanek** [comment]
Since this is useful to hint player at the fact that they don't have enough people for retal, we decided to gate this behind mcm option.

As for preventing an event-triggered narrative from playing we already have an example like that: https://github.com/WOTCStrategyOverhaul/SquadSelectAnytime/blob/8776c9d71b9b4256f93f8ca960c18b5aeb5378bc/SquadSelectAtAnyTime/Src/SquadSelectAtAnyTime/Classes/SSAAT_EventListener.uc#L26-L48

The gist: register a listener for that event with a much higher priority and `return ELR_InterruptListeners;` there
