### ISSUE TITLE
Improve SitReps

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#199]
https://docs.google.com/spreadsheets/d/15pBV7lLXxhPUYLFL0sB9f8coERp48C5VSCRpJ4B1ark/edit#gid=0

* There are ideas for more sitreps (compared to alpha 2 implementation)
* What happens to sitreps on non-infil missions?

*Transferred from trello during reorganization*

**Comment by Xymanek** [comment]
@ArcaneData1 you can start implementing "Running Start" and "Trojan" as T1 overinfil bonuses

**Comment by ChrisTheThinMint** [comment]
Result from discussion in chat:
- Trojan is rejected, it isnt universal enough and allows for cheese
- Running Start (2 mob in full cover) accepted, i replaced Familar Terrain (1 mob and 5 def in cover) with it, would like to keep the name "Familar Terrain" because "Running Start" sounds kinda strange.

Gonna need a decision of whether we want to adapt my SITREP suggestion. If you have any questions about why i arranged or balanced them in a certain way go ahead and mention me.

**Comment by Xymanek** [comment]
@ChrisTheThinMint can you write up a diff of your proposal (compared to current implementation)? These are the current risks:

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/e61ff4fbaa0cbb06b454e212def8cb7d49f4a443/CovertInfiltration/Config/XComInfiltration.ini#L255-L259

and these are the current bonuses (+ the risk removal)

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/e61ff4fbaa0cbb06b454e212def8cb7d49f4a443/CovertInfiltration/Config/XComInfiltration.ini#L275-L292

**Comment by cannonfodder1** [comment]
[Full Sitreps and Risks List](https://cdn.discordapp.com/attachments/496726597844467713/581764569761054720/unknown.png)
When a player selects a CI in the Covert Ops menu, and in that CI's loadout screen, they will be shown two possible Risks. When the CI reaches 100%, one of the two Risks will be chosen and revealed to the player, who can then choose to launch or overinfiltrate.
