### ISSUE TITLE
[IDEA] Lock down CAs during first month

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#202]
Lock down the CAs during first month to a predetermined set (eg. engineer, supplies, rookies, something like that). That way the campaign start isn't hugely determined by RNG

*Transferred from trello during reorganization*

**Comment by ChrisTheThinMint** [comment]
Locking down all CAs might not be such a good idea because it leads to static strategies (meta), but guaranteeing some is definitely the right approach. I would make sure that these three happen:
- Engineer rescue: Strategy layer is balanced around always getting one early, if you dont you are ****ed
- Either Rookies or Supplies
- #200 Black Market Reveal, putting it in month 1 is a bit earlier than Vanilla but might be better so that players have more flexibility early
