### ISSUE TITLE
Improve chosen spawning chance logic for infltrations

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#231]
Current logic:

* Get the chance based on num missions since the particular chosen was encountered - 0% for 1-2, 50% for 3 missions, 100% for 4+ missions
* Reduce it based on the infiltration modifier - 1 (no change) at 100% infil and 0.4 at 200% infil
* Apply dark event modifier (if currently active)
* Roll the chance

Now, I feel like this is really backwards from what we want to achieve - our logic in the end only reduces the overall chance for chosen to appear

My idea:
* Start from 40% for 1st mission since seen, 80% up to 4 missions and 100% for 4+
* Apply the infil and DE mod just as above and roll

**Comment by Xymanek** [comment]
We should also consider how we want to handle chosen chance for assault missions

**Comment by Thrawn007** [comment]
I think both get too extreme.  I don't like ever having a flat 0%, even
though the chosen is likely revering and licking wounds after an encounter.

Perhaps 10% for the 1st mission, and + 20% for each mission after, with
numbers ending over 100% after modification being 100%.
This means there is always a chance the chosen will show up, even if it's
unlikely, making it harder to game the system, but still meaning that
chosen has to recover a bit after a defeat.

Other things to consider is openings for new chosen skills they can train
in.
Fast recover - "The chosen's wounds recover quicker allowing them to return
to the field faster after defeat."  (Start at 30% instead of 10%, basically
boosting by 1 mission)
Thirst for vengeance - "The chosen's drive to strike back makes them more
aggressive, taking the field more often." (Boost by 30% instead of 20% for
each mission after the 1st)
