### ISSUE TITLE
Rework Overinfiltration Tiers

### ISSUE THREAD

**Issue by ChrisTheThinMint** [WOTCStrategyOverhaul/CovertInfiltration#232]
Infiltration should scale in 25% steps and up to 250% to improve overall scaling. Here are my suggested tiers:

125% - Opportune Moment: 10% Detection Radius Reduction, +5% crit
150% - Tier 1 SITREP
175% - Remove 1 risk
200% - Tier 2 SITREP
225% - Opportune Moment II: 20% Detection Radius Reduction, +10% crit
250% - Tier 3 SITREP

Other changes:
- Remove crit bonus from Mental Readiness, increase other bonuses to +15. Crit is too universal (and now reused in another effect) while the other bonuses are too weak, this should focus it more
- Change default overinfiltration caps to: 200% at +1, 150% at +2, 125% at +3, 100% at +4.

**Comment by cannonfodder1** [comment]
The issue I have with this idea is that the 125% bonus is barely noticable and at 150%, the T1 sitreps, by design, are meant to be mostly insignificant. That's 175%, almost twice the infil time, for the first decent effect. Why wouldn't I just go guns blazing at 100%? Even if I get wounded because of an unremoved risk, I would save a ton of time on infiltrating and have a lot more soldiers available.

**Comment by ChrisTheThinMint** [comment]
The main reason for this idea is that infiltration times are quite short right now, and from my own testing campaign i felt like i could always pick up the 133% and sometimes even the 166% bonus without any repercussions. I did of course consider that we can just up infil times too, but i think improving the depth of overinfiltration is better. To quote myself from discord:
"Overall, i'd like to shift it to a system where 125%-150% are almost freebies unless we're talking about a really heavily-armed squad, at 175-200% you should start to think about whether keeping soldiers dedicated longer is necessary, and 225-250% are real dedication"

Point taken about the strength of the first bonuses, though. I wouldnt mind making them a bit stronger, but stacking too many and too strong bonuses on XCOM wouldnt be good either. I'm gonna give it some thought.

**Comment by Thrawn007** [comment]
What if instead of a set bonus of "remove 1 risk", we could do things like "25% chance to remove 1 risk"
As a straw man, we could have a chart such as:
125% - 25% chance of Tier 1 SitREP, 5% chance to remove 1 risk
150% - 50% chance of Tier 1 SITREP, 10% chance to remove 1 risk
175% - 75% chance of Tier 1 SITREP, 25% chance to Remove 1 risk
200% - 100% chance of SITREP (50% Tier 1, 50% Tier 2), 50% chance to Remove 1 risk
225% - 100% chance of SITREP (25% Tier 1, 75% Tier 2), 75% chance to Remove 1 risk
250% - 100% chance of SITREP (25% Tier 1, 50% Tier 2, 25% Tier 3), 90% chance to Remove 1 risk

Roll the detection and crit bonuses into SitREPs instead of being their own items.  Multiple sitreps is also an option, but wanted a simple model for the strawman

**Comment by ChrisTheThinMint** [comment]
Thats a LOT of variability, and i dont think its necessary for the SITREPs as they already have random pools. Having a chance to remove a risk is an interesting idea though. Would the risk removal trigger instantly or would it just be an increasingly better chance and its rolled at mission start?

**Comment by Thrawn007** [comment]
My thought was at mission start, so you build up the %, but don't know the result until you arrive in battle.  If I understand things right, it would be too easy to just game the system if it was instant.  (You see that you hit your 5% chance, and you just go now.)

**Comment by Xymanek** [comment]
I think we go with Chris's initial plan but bump up Detection Radius Reduction to +15/+30. Otherwise Opportune Moment I is like 1 tile reduction which is almost nothing
