### ISSUE TITLE
Blacksite is revealed on map by scanning before seeing the cinematic

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#273]

**Comment by Xymanek** [comment]
Blocked by #255. We need to decide when the councilman screen first shows up as the blacksite cinematic is the council dude saying hi to commander

**Comment by Xymanek** [comment]
Ok, here is my idea:

* Council man shows up only for retals, facilities and GP missions
* Hide that screen for cases when it's redundant (eg. where it says only "progress chain") 
* For cases where it's still needed for chains, show the faction leader of the chain's faction
* Therefore, the blacksite mission will be unlocked after first attempted retal (this also makes sense, since that's when the ADVENT admin office will first hear about XCOM's commander - stuff before that is small resistance exploits together with factions from their POV)

cc @cannonfodder1 if you think that's good, I'll proceed with implementing this

**Comment by cannonfodder1** [comment]
I like this approach. I think the times when the screen is needed would be the Intel rewarding chains as the rewards there aren’t reflected in the loot recovered screen. It may be less work to simply make the faction leaders appear instead of the councilman and not worry about skipping the screen for some chains.
