### ISSUE TITLE
GTS still too weak

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#284]
It takes too long to setup and by that time everyone is promoted from doing CAs

Suggestion: enable the order that promotes to 3rd rank in GTS. Remove said order from pool. Increase project duration by 1.5

**Comment by Xymanek** [comment]
3rd rank is probably too good, make it 2nd rank

**Comment by bstar1million** [comment]
I think you need to be careful not to create scenario in which the optimal play is to not send rookies on missions/CAs and instead wait for the GTS to be finished so they start with a higher rank.

Perhaps instead of making this double promotion baseline, you could keep the order and add a GTS perk that costs X and increases all GTS promotions by one rank? And make the order give another 1 or 2 more ranks instead of a triple promotion.

**Comment by Xymanek** [comment]
The problem is that by the time the GTS is built (even as first facility) there are no rookies left since everyone is promoted by going on CAs

**Comment by bstar1million** [comment]
That is exactly what I mean: Getting the first promotion is super fast & easy, getting second one isn't. So making the base promotion 2 ranks might make it optimal to go on fewer CAs and missions in the beginning to make your soldiers from rookies into Corporals/Sergeants immediately.

**Comment by Xymanek** [comment]
I guess the correct approach is to change the GTS to allow to staff non-rookies there

**Comment by bstar1million** [comment]
That's actually an interesting idea. I think it just needs to be ensured that:
- it's not faster than going on missions
- you can't promote past a certain rank X, with X being determined by the resistance card/and or GTS perk(s) and the base max rank being Cpl. Perhaps it could go up to ~Major. That way you could get more use out of the facility in the late game.

**Comment by Xymanek** [comment]
> you can't promote past a certain rank X, with X being determined by the resistance card/and or GTS perk(s) 

Yeah, that was the idea

**Comment by Xymanek** [comment]
If we do this, we should scale training duration with the rank difference
