### ISSUE TITLE
GatherSupplies and GatherIntel chains cannot spawn

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#291]
They are not marked in deck and nothing in code spawns them directly

Additionally, I propose locking Supply Raid only to regions with radio relay built, to prevent it from showing up early (rewards too good)

**Comment by cannonfodder1** [comment]
> I propose locking Supply Raid only to regions with radio relay built, to prevent it from showing up early
XCOM's starting region has a radio relay though, so this wouldn't really do much

**Comment by Xymanek** [comment]
Welp, derp. Any other ideas, besides simply excluding starting region? I can come up with something like "in regions with link to a relay region", but that's kinda nuts

**Comment by bstar1million** [comment]
Aren't supply raids pretty much the only way to get Alien Alloys and Elerium Crystals (besides Black Market)? So in order to have any chance of upgrading your gear to T2, you'd have to first contact a region (and build a relay?) and then still wait for a supply raid to spawn. Even if you rush it, I think this would create some additional difficulty and would definitely limit your scanning choices on the geoscape in the early game.

**Comment by Xymanek** [comment]
I was pretty sure that the supply extraction mission (which is a different chain) also provided alloys and elerium. It's also the only mission that CI edits (to be evac-based)

**Comment by bstar1million** [comment]
Oh, my bad then. In that case, you should be guaranteed to get one of those early on imo.

**Comment by cannonfodder1** [comment]
I think we should lock the gather chains to the starting region and regions without radio towers, and have the supply raid and capture informant chains locked to radio tower regions. They are both superior over the gather/assault variants since you rarely get all the crates in supply extraction and in the capture informant chain you get an extra datapad.

**Comment by Xymanek** [comment]
Yeah, I could see that working
