### ISSUE TITLE
Implement system for enviromental sitreps

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#361]
Currently all sitreps (sans those which are forced by mission/plot type) are assigned as either bonuses or risks and thus added/removed accordingly. This leaves no place for things like "chemical leak" which are neither buff nor a debuff to the player.

I suggest that we implement "enviromental risks" SWO (which can be enabled/disabled during camapaign, but will affect only new missions spawned) which would allow the mission to roll for an additional sitrep from start which would not removable via the bonus system.

Internally, we could build a system that automatically generates the list from [all sitreps] - [risks] - [bonuses], so that mods that introduce new sitreps don't need explicit bridges (well, they would need a bridge only to mark their sitreps as risks/bonuses). Additionally, faction sitreps (#348) will use this to appear on missions

Need opinions

**Comment by cannonfodder1** [comment]
I think this is a good system, but I'm not so sure about having it as a SWO (which I think are disabled by default?). I think it should be an enabled-by-default config variable.

**Comment by Xymanek** [comment]
What if the SWO was inverted? I.e disabling the env sitreps? (cuz I know I would prefer to play without them)

**Comment by MrCloista** [comment]
SWO to turn off makes the most sense to me, call it 'Controlled Environment'.

**Comment by Xymanek** [comment]
I was thinking about "Pristine Battles" but "Controlled Environment" is probably better.

The question remains - how many? IMO there should be 1 environmental sitrep with 50% chance to show up

**Comment by MrCloista** [comment]
50% chance of 1, 10% chance of 2?

**Comment by Thrawn007** [comment]
10% of 2 does add some complications though.  We might have to mark some as mutually exclusive in that case.  For example, it wouldn't make sense to have "foggy conditions" limiting sight on the same mission as "bright conditions" which might extend sight, but give an extra chance of glancing blows due to glare.  It all depends on what these conditions are, but I think weather and lighting conditions are the ones that come to mind of exclusivity.  With that said, I like the idea of multiple conditions possible, even going as far as 50% of 1, 20% of 2, 5% of 3.

Some other considerations:
1) Might be worth having a resistance order or orders to "use the environment to your advantage" that could open up adding a preferred environmental condition with an additional level of infiltration.  Maybe you like "dusk assaults" because the range of your squad is optimized for the ranges and sight levels.

2) Might be worth keeping pools or tags on sitreps.  "Weather", "Lighting", "Factions", "Misc".  Have all sitreps go into Misc by default so that other mods work, but this may be an easy way to enforce exclusivity by only allowing 1 weather sitrep at a time, or 1 random faction to interfere at a time.

3) We need to make sure there are a number of sitreps that have small impacts, not major ones.  Then have the "zingers" that drastically alter things.  The majority should have enough impact to be noticable, but with 50% of missions having one, shouldn't be complete game changers.  If half the pool had major effects, and half minor, that means there is 25% of having a major effect and 25% of a minor assuming it's 50% chance of a sitrep.

**Comment by Xymanek** [comment]
>  We might have to mark some as mutually exclusive in that case

We already have a system for that in place:

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/f12cf8583fa75d0fc019e3e17884b9407e8a4c73/CovertInfiltration/Config/XComGameData.ini#L117-L121

My main concern about allowing more than 1 environmental sitrep is that it risks rolling tons of crap on P2+ and thus the player would have to abandon the chain. Therefore I would to have just 0 or 1 of environmental sitreps

Comments on the bullet points:

1)  Overinfil is very defined now, I do not see a point of adding cards to it
2) Again, do not see a point. If the sitreps are mechanically incompatible or meaningless together (eg +timer and -timer) then just mark them as such
3) See my concern above
