### ISSUE TITLE
Split off smaller features into submods

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#381]
In order to make Strategy Overhaul a more modular experience, we should separate several of Covert Infiltration's smaller features into submods that can work both with and without Covert Infiltration. They shouldn't go on the workshop until shortly before the big release, but they can sit on our github page and have compiled releases ready for people if they want them.

Submod Ideas:
Strategy Overhaul: Research and Development (proving ground changes)
Strategy Overhaul: Prototype Armoury (single-build items and prototypes)
Strategy Overhaul: Supply Evacuation (supply extraction mission changes)
Strategy Overhaul: Living Space (crew size limit and upgrades)

**Comment by Xymanek** [comment]
1) Not sure about "Strategy Overhaul: " part in names... Feels like the names just become unwieldy
2) Supply evac rework is bad as a separate mod cuz (a) it's a straight nerf compared to vanilla supply evac and (b) it depends on our rnf manager which is used for the rfn UI changes, so doing that from 2 different mods will be a pain
3) Living Space - i see no use for that in vanilla campaign, since it's just a nerf to xcom. Additionally the balance is for CI and I don't think it makes sense to also balance it for vanilla or something
4) Individual build could work as a standalone mod, but again, I think we will need to untangle some internal dependencies. Also, could probably come up with a better name... How about "Shen Isn't A Magician" 😂 

Also, the improved sitrep details screen should really become a standalone mod. It has no dependencies on other stuff and I really cringe every time I watch odd look at the vanilla one, knowing how messed up it is

**Comment by Xymanek** [comment]
A couple more concerns about the individual build:

* The changes are balanced for CI, no clue how they would work in vanilla
* Having it as a separate (but required) mod may cause some players to feel like it's optional... which it's not. I would prefer if players had no choice in this matter

**Comment by boundir** [comment]
I've always played with single builds before CI and didn't have the luxury to swap attachments or multiple loots per missions.
I think adding those plus the POI for TLE weapons is good enough to make it a standalone mod.

And you don't have to remove it from CI because it's meant to be played with it.

**Comment by ChrisTheThinMint** [comment]
I suggested Living Space as a split-off mod because it provides an interesting option for people to balance their own game or add in some more realism. I dont think its too difficult to make up a few numbers for vanilla, and beyond that it can be more of a "tweak it yourself" mod.

**Comment by cannonfodder1** [comment]
If you really want to hard require people to have these mods @Xymanek, you can make a popup on the main menu that checks to see if anything is missing then informs the player that these mods are not optional. Then they hit the OK button and the game closes. Or something like that, if we don’t have access to application shutdown I’m sure we can just construct some code that crashes the game when the button is pressed.

The problem is, even if you include them in CI they are still going to be optional if players choose to wipe the singlebuild arrays and set barracks limit to 999 in the config files. Even if you remove the config options, other people will make mods that expose them to config for people who want to adjust their experience. Trying to force people into installing something they don’t want to install has always been a lost cause.

**Comment by cannonfodder1** [comment]
Discussions on discord have concluded that the only submod that will be split off is Research and Development, which will include the single-build system, prototypes feature, and all the stuff in production overhaul. This will be done at some point before Beta 3 and is waiting for #336 to be completed

**Comment by Xymanek** [comment]
Ok, so after thinking about this for quite a while I the following 3 mods should be split off:

* **Prototype Armoury**: Individual-build items and prototypes
* **Living Space**: Crew size limit and upgrades
* **Better SITREPs Report**: Replacement of `UISitRepInformation`

The production overhaul stuff IMO should not be something we worry about now - we have too much work already, it's not required for CI and it's still too alpha right now. We can focus on it and release it as a separate mod later.

Beyond the basic need to untangle the code from CI's classes (CIInfo, DLCInfo, Helper, EventListener are the major places) we also will need to:

* Setup the repo/project - build script (+ msbuild adjustments), CHL submodule, etc
* Maintain workshop pages - descriptions, images, logo, etc
* Decide on whether we will leave an integrated version inside CI (like lw2 did) or have CI depend on these "new" mods
  * If CI depends, then
    * We may have a harder time updating configs in future (for whatever reason)
    * Individual-build configs from bridges will apply to both CI and non-CI usages of the individual-build (is that good? see below)
  * If CI doesn't depend, then
    * Higher chance of misunderstanding what requires what by players (especially when 3rd party mods start getting involved)
    * Individual-build configs from bridges will not apply to non-CI usages of the individual-build (is that good? see below)
      * Unless we separate single-build stuff into a separate script package inside CI, so that config headers match
    * We double work for ourselves when there is a need for updates
      * We could also keep everything inside CI (as per suggestion above) and then use git trickery to split subtrees into standalone repos/projects. For example see https://github.com/symfony/form which is "derived" from https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Form. The downside here is that we are getting into a "very complex tooling" land and I would like to avoid that (since no one except me will be able to understand it)

Regarding whether individual-build configs from bridges will (or not) apply to non-CI usages of the individual-build:

* Good
  * Less work for people implementing bridges
  * Less confusion by players
* Bad
  * Intended CI and non-CI values may not match (due to higher number of simultaneously used items in CI), making the whole bridge story more confusing

So, some facts + IMO whether should split

Submod | Depends on CHL | Pending CHL PRs | Should split
-------- | ------------------ | ----------------- | -------------
**Prototype Armoury** | Yes | None | Yes
**Living Space** | Yes | [#727](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/727) | Yes
**Better SITREPs Report** | No | N/A | Yes

P.S. I'm probably forgetting something, but this should be a good start for a discussion.
P.P.S. Nothing here is set in stone and can change (eg. if we find a better approach) - especially the "Better SITREPs Report" name 😂

**Comment by Xymanek** [comment]
Need a name for `UISitRepInformation` replacement. "Better SITREPs Report" is too bad...

@cannonfodder1 @ChrisTheThinMint

**Comment by cannonfodder1** [comment]
Show SitRep Details
SitRep Info Extended
SitRep Report

**Comment by Xymanek** [comment]
> SitRep Report

Situation Report Report 😂 

> Show SitRep Details

Vanilla already does that, just in a very backwards way when > 1 sitreps

> SitRep Info Extended

I guess? Feels sorta "weak", less cacth-y than the rest of our names

**Comment by Xymanek** [comment]
We should also split the disguises into a separate mod. It should come with vanilla schematic-based building but also include config for Prototype Armoury, so that they become individual build when used together

**Comment by Xymanek** [comment]
All split off PRs are merged, closing this issue
