### ISSUE TITLE
Limit counter DE chains to one per region

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#400]
This will back back vanilla behaviour where if you didn't contact a region before first supply drop, you will be able to counter only 1 of the DEs.

However, in CI you cannot contact a region before first supply drop (since the tech unlocks after first retal which is right before supply drop + research/scan times).

Need discuss.

**Comment by cannonfodder1** [comment]
I don't think this is a good idea because of the previously mentioned inability to get two regions by the first supply drop. There are two possible solutions:
1. the first DE cycle is already limited to two DEs, we could limit it to one
2. we could start the campaign with two regions already contacted

**Comment by Xymanek** [comment]
> the first DE cycle is already limited to two DEs, we could limit it to one

I like that - the next cycle is 2 and the 3rd (and latter) is 2+locked one. Will help counter the slow start of CI cuz everything is in chains

> we could start the campaign with two regions already contacted

That's gonna be stupid lore-wise - we already have 2 regions contacted but we need to learn a tech on how to do it after waiting for some dude to call us

**Comment by cannonfodder1** [comment]
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/711
