### ISSUE TITLE
[Beta 2] First retal spawned with only Comms Jamming sitrep

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#428]
![image](https://user-images.githubusercontent.com/2865341/72879461-94df1480-3d05-11ea-9a94-6bc6e758289d.png)

The only case where this should be possible is if all the risks are not eligible, which should not be the case

**Comment by cannonfodder1** [comment]
Can confirm this bug, I think it's because we've locked off all flat risk sitreps that are available to Retaliation mission types at low Force Levels. I suppose I'll unblock ADVENT Air Patrols because it's the least conflicting with the mission type, but we may want to consider adding additional flat risks and tier 1 bonuses.

**Comment by Xymanek** [comment]
Additional RNF drop would be pretty penalizing on first retal.... I think we def need something else

**Comment by cannonfodder1** [comment]
Pool of possible new sitreps that I'll start developing is here: https://docs.google.com/spreadsheets/d/1l4JkXCDOmHsdlmYhI67VcD4XKsvPa-Mre4zQf6fXAeI/edit?usp=sharing

**Comment by cannonfodder1** [comment]
SITREPs sheet edited to reflect changes and what's actually being implemented for Beta 3. Discussion of them should be moved to issue #499 

As for resolving this issue, Retaliations will simply not spawn any random positive or negative sitreps, as they are too different of a mission type. This also makes them more consistent which is good because they are the only mission where failing actually punishes the player.
