### ISSUE TITLE
Supply extraction possible cheese

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#611]
At the moment, the RNFs and advent extraction will not start while the squad is concealed. However, if the concealed xcom sees a pod from 2 different teams (and these 2(+) pods see each other), the pods will activate.

In theory it can allow player to wait until the AIs clear out themselves and then xcom sweeps the battlefield practically unobstructed, although this is a very unlikely scenario.
In practice, this can help a lot with the initial attack, as all enemies will be distracted with each other, and some even dead

P.S. Thanks to DerAva for considering this tactic 😁

**Comment by nfma** [comment]
This is a tactic that I’ve used extensively and effectively, it works specially well with the lost as third party since the AI ignores the lost altogether if there’s no XCOM in sight. Ive cleaned entire maps just by moving around my soldiers and breaking concealment to kill the remaining lost. I wouldn’t say it’s an unlikely scenario, it does require patience from a player’s perspective though.
